
tasks:
  - name: install System
    init: |
      pyenv install 3.11.6
      pyenv global 3.11.6
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install --upgrade --pre robotframework
      rfbrowser init
      npx --yes playwright install-deps
image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    onOpen: open-preview
    visibility: private
vscode:
  extensions:
    - ms-python.python
    - d-biehl.robotcode
    - PKief.material-icon-theme
